### Basics
GET http://127.0.0.1:8000/basics?ticker=AAPL

### Proforma (stock deal)
POST http://127.0.0.1:8000/proforma
Content-Type: application/json

{
  "acquirer": "AAPL",
  "target": "ADBE",
  "structure": {
    "type": "stock",
    "exchange_ratio": 0.20,
    "synergies_pre_tax": 1000000000,
    "tax_rate": 0.21,
    "ppa_amort_post_tax": 200000000
  }
}

### Proforma (cash deal with new debt)
POST http://127.0.0.1:8000/proforma
Content-Type: application/json

{
  "acquirer": "MSFT",
  "target": "CRM",
  "structure": {
    "type": "cash",
    "new_debt": 5000000000,
    "cost_of_debt": 0.05,
    "synergies_pre_tax": 500000000,
    "tax_rate": 0.25
  }
}